morning_quotes = [
    "Good morning! ☀️ Start your day with a smile and a positive thought. 😊",
    "Rise and shine! 🌟 Your future is created by what you do today. 💪",
    "Wishing you a day full of joy and success! 🌸✨",
    "Good morning! Every sunrise is an invitation to brighten someone’s day. 🌅",
    "Today is a new day! 🌈 Embrace it with enthusiasm and energy. 🚀",
    "Good morning! ☕️ Let’s make today amazing and memorable. 🌟",
    "Rise and shine! 🌞 Remember, success begins with the first step. 👣",
    "Good morning! 🌼 Be the reason someone smiles today. 😊",
    "Every morning is a chance to start over. 🌅 Seize it! 💫",
    "Wake up and be awesome! 🌟 Your attitude determines your altitude. 🚀",
    "Good morning! 🌞 Believe in yourself and all that you are. 💖",
    "Rise with determination, go to bed with satisfaction. 🌟✨",
    "Morning! 🌸 Chase your dreams and make them a reality. 💪",
    "Today is a gift. 🎁 Open it with joy and excitement. 🌟",
    "Good morning! ☀️ Take time to enjoy the little things today. 🌼",
    "Rise and grind! 🌟 Success is earned one day at a time. 💪",
    "Good morning! 🌞 Make today count and be proud of your accomplishments. 💖",
    "Every sunrise is a new beginning. 🌅 Make it count. 💫",
    "Good morning! 🌼 Today’s opportunities are a result of yesterday’s efforts. 🚀",
    "Wake up with a smile and go after your dreams. 🌈✨",
    "Good morning! ☀️ Embrace today with an open heart and a positive mindset. 😊",
    "Rise and shine! 🌟 Your dreams are worth fighting for. 💪",
    "Good morning! 🌼 Believe in the magic of new beginnings. ✨",
    "Every morning is a chance to live life to the fullest. 🌟 Make the most of it! 💫",
    "Good morning! ☀️ Success is the sum of small efforts repeated daily. 💪",
    "Wake up with purpose and enthusiasm! 🌈 Your day awaits. 🚀",
    "Good morning! 🌸 You have the power to create your own destiny. 🌟",
    "Rise with confidence and conquer your day! 💪✨",
    "Good morning! 🌞 Believe in yourself and all that you are capable of. 💖",
    "Every day is a new beginning. 🌅 Embrace it with hope and optimism. 🌟",
    "Good morning! ☕️ The secret to getting ahead is getting started. 🚀",
    "Wake up and take action! 🌟 Success is just a step away. 💪",
    "Good morning! 🌼 Your journey to success begins with a single step. 🌈",
    "Rise and shine! ☀️ Today is the perfect day to start something new. 💫",
    "Good morning! 🌸 Make today memorable with positivity and action. 🌟",
    "Wake up and be amazing! 🌟 Your potential is limitless. 🚀",
    "Good morning! 🌞 Embrace the challenges of today with courage and strength. 💪",
    "Every day is a fresh start. 🌅 Make it count! 🌟",
    "Good morning! ☕️ Let your passion drive you to achieve greatness. 🌈",
    "Rise and conquer! 🌟 Today is an opportunity to achieve your dreams. 💪",
    "Good morning! 🌼 The key to success is to focus on goals, not obstacles. 🚀",
    "Wake up with determination and go to bed with satisfaction. 🌟✨",
    "Good morning! ☀️ Today is a new chance to pursue your dreams. 🌈",
    "Rise and shine! 🌟 Your hard work will lead to success. 💪",
    "Good morning! 🌸 Start each day with a positive attitude and watch the magic unfold. ✨",
    "Wake up and be the best version of yourself today! 🌈🚀",
    "Good morning! 🌞 Believe in your dreams and make them a reality. 💖",
    "Every morning is a new opportunity to create a better future. 🌟",
    "Good morning! ☕️ Success comes from preparation and hard work. 💪",
    "Rise and shine! 🌅 Today is the perfect day to make your dreams come true. 💫",
    "Good morning! 🌼 Let go of yesterday’s worries and focus on today’s possibilities. 🌟",
    "Wake up with enthusiasm and see where the day takes you! 🚀💫",
    "Good morning! 🌞 Your future is bright and full of endless possibilities. 🌈",
    "Every day is a chance to write your own story. 🌟 Make today unforgettable. 💖",
    "Good morning! ☕️ Embrace today’s challenges with a positive mindset. 💪",
    "Rise and shine! 🌸 Success is a journey, not a destination. 🌟",
    "Good morning! 🌼 Each day is a new opportunity to learn and grow. 🌟",
    "Wake up and take on the day with confidence and determination! 💪🚀",
    "Good morning! ☀️ Your attitude today will determine your success tomorrow. 🌟",
    "Rise and conquer your goals with passion and dedication! 🌟✨",
    "Good morning! 🌞 Make every moment count and live life to the fullest. 🌈",
    "Every sunrise is a chance to make a difference. 🌟 Embrace it! 💖",
    "Good morning! ☕️ Believe in yourself and all that you can achieve. 💪",
    "Wake up with purpose and let your dreams guide you today. 🚀🌟",
    "Good morning! 🌼 Success is the result of preparation and perseverance. 🌈",
    "Rise and shine! 🌞 Today is your day to shine and achieve greatness. 💫",
    "Good morning! 🌸 Make today a day to remember by staying positive and motivated. 🌟",
    "Wake up and be awesome! 🌟 Your potential is limitless. 🚀",
    "Good morning! 🌞 Believe in your abilities and let your dreams take flight. 💖",
    "Every morning is a fresh start. 🌅 Make today extraordinary! 🌟",
    "Good morning! ☕️ Your hard work and dedication will lead to success. 💪",
    "Rise and conquer! 🌟 Today is full of new opportunities. 🌈",
    "Good morning! 🌼 Let your passion and enthusiasm guide you to success. 🌟",
    "Wake up and embrace the day with a positive mindset! 🌞🚀",
    "Good morning! ☀️ The best way to predict the future is to create it. 🌈",
    "Rise and shine! 🌟 Today is a new opportunity to achieve your goals. 💫",
    "Good morning! 🌸 Focus on your dreams and let nothing stop you. 🌟",
    "Wake up with determination and let your goals inspire you! 🚀💪",
    "Good morning! 🌞 Your potential is endless, so reach for the stars. 🌟",
    "Every day is a new chance to shine and achieve greatness. 🌅💫",
    "Good morning! ☕️ Let today be a day of success and joy. 🌈",
    "Rise and shine! 🌟 Your dreams are within reach, so go for them! 💪",
    "Good morning! 🌼 Embrace each day with enthusiasm and positivity. 🌟",
    "Wake up and make today amazing! 🚀 Your efforts will pay off. 💫",
    "Good morning! ☀️ Believe in yourself and create the life you desire. 🌈",
    "Rise and conquer your goals with a positive attitude! 🌟💪",
    "Good morning! 🌸 Every day is a new beginning, so make it count. 💫",
    "Wake up and take charge of your day with confidence and courage! 🚀🌟",
    "Good morning! 🌞 Your journey to success starts with a positive mindset. 🌈",
    "Every sunrise is an opportunity to pursue your dreams. 🌅💪",
    "Good morning! ☕️ Let your passion drive you towards your goals. 🌟",
    "Rise and shine! 🌟 Today is a day full of possibilities and opportunities. 💫",
    "Good morning! 🌼 Embrace each moment with a positive attitude and joy. 🌈",
    "Wake up and achieve greatness today! 🚀 Your hard work will pay off. 💪",
    "Good morning! 🌞 Believe in yourself and make today extraordinary. 🌟",
    "Every morning is a chance to make a difference. 🌅 Embrace it! 💫",
    "Good morning! ☕️ Your success is a result of your hard work and dedication. 🌈",
    "Rise and shine! 🌟 Today is your day to shine and achieve your dreams. 💫",
    "Good morning! 🌸 Make each moment of today count and live with purpose. 🌟",
    "Wake up with enthusiasm and let your goals guide you! 🚀💪",
    "Good morning! 🌞 Your potential is limitless, so reach for the stars. 🌟",
    "Every day is a new opportunity to succeed",
]